site_name: BrowserBee Selenium Operator
site_url: "https://docs.browserbee.io"

theme:
  name: material
  features:
    - navigation.top
  palette:
    primary: blue
    accent: blue

nav:
  - Home: documentation/index.md
  - Downloads:
      - Selenium Operator: downloads/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/browserbee
