---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - selenium-grid.browserbee.io
  resources:
  - seleniumgrids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-grid.browserbee.io
  resources:
  - seleniumgrids/finalizers
  verbs:
  - update
- apiGroups:
  - selenium-grid.browserbee.io
  resources:
  - seleniumgrids/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - selenium-hub.browserbee.io
  resources:
  - seleniumhubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-hub.browserbee.io
  resources:
  - seleniumhubs/finalizers
  verbs:
  - update
- apiGroups:
  - selenium-hub.browserbee.io
  resources:
  - seleniumhubs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - selenium-node.browserbee.io
  resources:
  - seleniumnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-node.browserbee.io
  resources:
  - seleniumnodes/finalizers
  verbs:
  - update
- apiGroups:
  - selenium-node.browserbee.io
  resources:
  - seleniumnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - selenium-standalone.browserbee.io
  resources:
  - seleniumstandalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-standalone.browserbee.io
  resources:
  - seleniumstandalones/finalizers
  verbs:
  - update
- apiGroups:
  - selenium-standalone.browserbee.io
  resources:
  - seleniumstandalones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - selenium-workflow.browserbee.io
  resources:
  - seleniumworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-workflow.browserbee.io
  resources:
  - seleniumworkflows/finalizers
  verbs:
  - update
- apiGroups:
  - selenium-workflow.browserbee.io
  resources:
  - seleniumworkflows/status
  verbs:
  - get
  - patch
  - update
