# permissions for end users to edit seleniumworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: seleniumworkflow-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: browserbee-selenium-operator
    app.kubernetes.io/part-of: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumworkflow-editor-role
rules:
- apiGroups:
  - selenium-workflow.browserbee.io
  resources:
  - seleniumworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-workflow.browserbee.io
  resources:
  - seleniumworkflows/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
