# permissions for end users to edit seleniumstandalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: seleniumstandalone-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: browserbee-selenium-operator
    app.kubernetes.io/part-of: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumstandalone-editor-role
rules:
- apiGroups:
  - selenium-standalone.browserbee.io
  resources:
  - seleniumstandalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selenium-standalone.browserbee.io
  resources:
  - seleniumstandalones/status
  verbs:
  - get
