apiVersion: selenium-node.browserbee.io/v1
kind: SeleniumNode
metadata:
  labels:
    app.kubernetes.io/name: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumnode-sample
spec:
  hubRef:
    name: seleniumhub-sample
    namespace: default
  image: selenium/node-chromium:latest
  replicas: 2

