apiVersion: selenium-hub.browserbee.io/v1
kind: SeleniumHub
metadata:
  labels:
    app.kubernetes.io/name: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumhub-sample
spec:
  image: selenium/hub:4.21.0
  replicas: 1
  serviceType: ClusterIP
  port: 4444
