apiVersion: selenium-standalone.browserbee.io/v1
kind: SeleniumStandalone
metadata:
  labels:
    app.kubernetes.io/name: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumstandalone-sample
spec:
  # TODO(user): Add fields here
