apiVersion: selenium-hub.browserbee.io/v1
kind: SeleniumHub
metadata:
  labels:
    app.kubernetes.io/name: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumhub-sample
spec:
  version: 4.21.0
  logLevel: INFO
  enableTracing: false


