apiVersion: selenium-node.browserbee.io/v1
kind: SeleniumNode
metadata:
  labels:
    app.kubernetes.io/name: browserbee-selenium-operator
    app.kubernetes.io/managed-by: kustomize
  name: seleniumnode-sample
spec:
  hubRef:
    name: seleniumhub-sample
    namespace: default
  browser: chromium
  version: latest
  replicas: 1
  screenWidth: 1920
  screenHeight: 1080
  screenDepth: 24
  screenDPI: 96
  maxSessions: 2
  sessionTimeout: 30

 